# Generated by Django 5.2 on 2025-04-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('coop_requirements', models.TextField()),
                ('posting_date', models.DateField()),
                ('expiartion_date', models.DateField()),
                ('start_date', models.DateField()),
                ('discription', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.companyprofile')),
                ('major', models.ManyToManyField(to='profiles.major')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField()),
                ('cover_letter', models.FileField(upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile')),
                ('coop_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.coopposting')),
            ],
        ),
    ]
