# Generated by Django 4.2.20 on 2025-04-29 03:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_personalinformation_picture'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.studentprofile'),
        ),
        migrations.CreateModel(
            name='CoopOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('application_deadline', models.DateField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coop_opportunities', to='profiles.companyprofile')),
                ('majors', models.ManyToManyField(related_name='coop_opportunities', to='profiles.major')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='posts.coopopportunity'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'opportunity')},
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='coop_posting',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.DeleteModel(
            name='CoopPosting',
        ),
    ]
