# Generated by Django 5.2 on 2025-04-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coopposting',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coopposting',
            old_name='expiartion_date',
            new_name='expiration_date',
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='coopposting',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
