# Generated by Django 4.2.20 on 2025-04-29 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_personalinformation_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_application_applied_at_application_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration', models.CharField(help_text='e.g., 3 months, 1 semester', max_length=50)),
                ('application_deadline', models.DateField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_opportunities', to='profiles.companyprofile')),
                ('majors_needed', models.ManyToManyField(related_name='training_opportunities', to='profiles.major')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='posts.application')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='posts.trainingopportunity'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('opportunity', 'student')},
        ),
        migrations.DeleteModel(
            name='CoopOpportunity',
        ),
    ]
