# Generated by Django 5.2 on 2025-05-03 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_application_applied_at_and_more'),
        ('profiles', '0023_alter_companyprofile_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingopportunity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='trainingopportunity',
            name='description',
            field=models.TextField(default='Details of this opportunity will be added soon.'),
        ),
        migrations.AddField(
            model_name='trainingopportunity',
            name='title',
            field=models.CharField(default='Co-op Opportunity', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message to the company'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.city'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='profiles.companyprofile'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='duration',
            field=models.CharField(help_text="e.g., '3 months', '6 weeks'", max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='majors_needed',
            field=models.ManyToManyField(related_name='opportunities', to='profiles.major'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DRAFT', 'Draft'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20),
        ),
    ]
