# Generated by Django 5.2 on 2025-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'تحت المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('WITHDRAWN', 'تم الانسحاب')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('EXPIRED', 'منتهي الصلاحية'), ('DRAFT', 'مسودة'), ('CLOSED', 'مغلق')], default='ACTIVE', max_length=20),
        ),
    ]
