# Generated by Django 5.2 on 2025-04-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='arabic_name',
        ),
        migrations.AddField(
            model_name='country',
            name='english_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
