# Generated by Django 5.2 on 2025-04-22 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='uni_name',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='picture',
            field=models.ImageField(blank=True, default='profiles/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(upload_to='certs/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='address_line1',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='address_line2',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='commercial_CRM_Certificate',
            field=models.FileField(upload_to='crm_certs/'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='commercial_register',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='industry',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='major',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='full_name_ar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='full_name_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile'),
        ),
    ]
