# Generated by Django 5.2 on 2025-04-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_education_uni_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='CompanyAddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.companyaddress'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='commercial_register',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
