# Generated by Django 5.2 on 2025-04-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_personalinformation_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='profiles.studentprofile'),
        ),
    ]
