# Generated by Django 5.2 on 2025-04-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_skill_proficiency_alter_skill_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم'), ('اللغة الأم', 'اللغة الأم')], max_length=20),
        ),
    ]
