# Generated by Django 5.2 on 2025-04-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_language_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='profiles.studentprofile'),
        ),
    ]
