# Generated by Django 5.2 on 2025-04-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_studentprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(null=True)),
                ('address_line', models.TextField(null=True)),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.city')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile')),
            ],
        ),
    ]
