# Generated by Django 5.2 on 2025-04-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_contactinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
