# Generated by Django 5.2 on 2025-04-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_education_gpa_scale_alter_education_gpa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='name',
            new_name='ar_name',
        ),
        migrations.AddField(
            model_name='major',
            name='en_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
