# Generated by Django 5.2 on 2025-04-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_name_major_ar_name_major_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa_scale',
            field=models.PositiveSmallIntegerField(choices=[('4', '4'), ('5', '5'), ('100', '100')], null=True),
        ),
    ]
