# Generated by Django 5.2 on 2025-04-23 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_contactperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='profiles.studentprofile'),
        ),
    ]
