# Generated by Django 5.2 on 2025-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_contactinformation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduating_date',
            field=models.DateField(null=True),
        ),
    ]
