# Generated by Django 5.2 on 2025-04-25 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_education_gpa_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='profiles.studentprofile'),
        ),
    ]
