# Generated by Django 5.2 on 2025-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_education_graduating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
