# Generated by Django 5.2 on 2025-04-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='address_line',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='full_name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
