# Generated by Django 5.2 on 2025-04-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_experience_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
