# Generated by Django 5.2 on 2025-04-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_personalinformation_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='arabic_name',
        ),
        migrations.AddField(
            model_name='city',
            name='english_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
