# Generated by Django 5.2 on 2025-04-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_rename_name_city_arabic_name_city_english_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='full_name_ar',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='full_name_en',
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=4, null=True),
        ),
    ]
