# Generated by Django 5.2 on 2025-04-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_rename_full_name_ar_personalinformation_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[(' b', ' الثانوية العامة أو ما يعادلها'), ('دبلوم', 'دبلوم'), ('بكالوريوس', 'بكالوريوس'), ('دبلوم عالي', '  دبلوم عالي'), ('ماجستير', 'ماجستير'), (' دكتوراة', '  دكتوراة')], max_length=100),
        ),
    ]
