# Generated by Django 5.2 on 2025-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('HIGH_SCHOOL', 'الثانوية العامة أو ما يعادلها'), ('DIPLOMA', 'دبلوم'), ('BACHELOR', 'بكالوريوس'), ('POST_DIPLOMA', 'دبلوم عالي'), ('MASTER', 'ماجستير'), ('DOCTORATE', 'دكتوراه')], max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa_scale',
            field=models.PositiveSmallIntegerField(choices=[('4', '4.0'), ('5', '5.0'), ('100', '100.0')], null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('BEGINNER', 'مبتدئ'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'متقدم'), ('NATIVE', 'اللغة الأم')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'ذكر'), ('FEMALE', 'أنثى')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('BEGINNER', 'مبتدئ'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'متقدم')], max_length=20),
        ),
    ]
