# Generated by Django 5.2 on 2025-04-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_education_degree_alter_education_gpa_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='picture',
            field=models.ImageField(blank=True, default='profiles/profile_images/default.png', null=True, upload_to='profiles/profiles_images/'),
        ),
    ]
