# Generated by Django 5.2 on 2025-05-01 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_personalinformation_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='company_address',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='commercial_CRM_Certificate',
            new_name='crm_certificate',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address_line',
            field=models.CharField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='company_profile',
            field=models.OneToOneField(default=2019, on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='profiles.companyprofile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyAddress',
        ),
    ]
