# Generated by Django 5.2 on 2025-05-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_personalinformation_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_address',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='commercial_CRM_Certificate',
            new_name='crm_certificate',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, default='company_logos/default.png', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='company_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='profiles.companyprofile'),
        ),
        migrations.DeleteModel(
            name='CompanyAddress',
        ),
    ]
