# Generated by Django 5.2 on 2025-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_companyprofile_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address_line',
            field=models.CharField(max_length=100),
        ),
    ]
