# Generated by Django 5.2 on 2025-05-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_contactperson_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(default='company_logos/default.png', upload_to='company_logos/'),
        ),
    ]
