# Generated by Django 5.2 on 2025-05-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_companyprofile_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='name',
            new_name='arabic_name',
        ),
        migrations.AddField(
            model_name='industry',
            name='english_name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
