# Generated by Django 4.2.20 on 2025-05-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_rename_name_industry_arabic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_location',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
