# Generated by Django 5.2 on 2025-05-05 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_companyprofile_company_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfileEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('commercial_register', models.CharField(max_length=200)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('crm_certificate', models.FileField(blank=True, null=True, upload_to='crm_certs/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='profiles.companyprofile')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.industry')),
            ],
        ),
    ]
