# Generated by Django 5.2 on 2025-05-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_companyprofileeditrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofileeditrequest',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='companyprofileeditrequest',
            name='logo',
        ),
        migrations.AddField(
            model_name='companyprofileeditrequest',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.city'),
        ),
    ]
