# Generated by Django 5.2 on 2025-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_companyprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofileeditrequest',
            name='company_url',
            field=models.URLField(default=2018),
            preserve_default=False,
        ),
    ]
