# Generated by Django 5.2 on 2025-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_companyprofileeditrequest_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofileeditrequest',
            name='company_url',
            field=models.URLField(null=True),
        ),
    ]
