# Generated by Django 5.2 on 2025-05-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_alter_companyprofileeditrequest_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofileeditrequest',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
