# Generated by Django 5.2 on 2025-05-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_alter_companyprofileeditrequest_company_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofileeditrequest',
            old_name='company_url',
            new_name='company_location',
        ),
    ]
